# set tabstop=2 shiftwidth=2 expandtab
# jdbc:postgresql://postgresql-confluence:5432/confluence_db1

version: '2'

##################
#### SERVICES ####
##################

services:

  ######################
  #### APPLICATIONS ####
  ######################
  
  jiramz8:
    image: cptactionhank/atlassian-jira:7.2.4
    container_name: jiramz8
    hostname: jiramz8
    networks:
      - mz8-network-1
    volumes:
      - jiradata:/var/atlassian/jira
    links:
      #- 'mysql-jira:mysql-jira'
      - 'postgresql-jira:postgresql-jira'

  confluencemz8:
    image: blacklabelops/confluence:6.1.2
    container_name: confluencemz8
    hostname: confluencemz8
    networks:
      - mz8-network-1
    ports:
      - '8085:8090'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME='
      - 'CONFLUENCE_PROXY_PORT='
      - 'CONFLUENCE_PROXY_SCHEME='
      - 'CONFLUENCE_DELAYED_START='
    volumes:
      - confluencedatavar:/var/atlassian/confluence
      - confluencedataopt:/opt/atlassian/confluence
    links:
      #- 'mysql-confluence:mysql-confluence'
      - 'postgresql-confluence:postgresql-confluence'

  owncloud:
    image: owncloud
    container_name: owncloud
    hostname: owncloud
    networks:
      - mz8-network-1
    volumes:
      - owncloud:/var/www/html
    links:
      - 'mysql-oc:mysql-oc'


  ###################  
  #### DATABASES ####
  ###################

  postgresql-jira:
    image: blacklabelops/postgres
    container_name: postgresql-jira
    hostname: postgresql-jira
    networks:
      - mz8-network-1
    volumes:
      - postgresql-jira:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jira'
      - 'POSTGRES_DB=jira_db1'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
  
  postgresql-confluence:
    image: blacklabelops/postgres
    container_name: postgresql-confluence
    hostname: postgresql-confluence
    networks:
      - mz8-network-1
    volumes:
      - postgresql-confluence:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=confluence'
      - 'POSTGRES_PASSWORD=confluence'
      - 'POSTGRES_DB=confluence_db1'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

#  mysql-jira:
#    image: mysql:5.6
#    container_name: mysql-jira
#    hostname: mysql-jira
#    networks:
#      - mz8-network-1
#    volumes:
#      - mysqldata-jira:/var/lib/mysql
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=root'
#      - 'MYSQL_DATABASE=jira_db1'
#      - 'MYSQL_USER=jira'
#      - 'MYSQL_PASSWORD=jira'
#  
#  mysql-confluence:
#    image: mysql:5.6
#    container_name: mysql-confluence
#    hostname: mysql-confluence
#    networks:
#      - mz8-network-1
#    volumes:
#      - mysql-confluence:/var/lib/mysql
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=root'
#      - 'MYSQL_DATABASE=confluence_db1'
#      - 'MYSQL_USER=confluence'
#      - 'MYSQL_PASSWORD=confluence'
 
  mysql-oc:
    image: mysql:5.6
    container_name: mysql-oc
    hostname: mysql-oc
    networks:
      - mz8-network-1
    volumes:
      - mysqldata-oc:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=oc_db1'
      - 'MYSQL_USER=oc'
      - 'MYSQL_PASSWORD=oc'


  #######################
  #### REVERSE PROXY ####
  #######################

  httpd:
    image: httpd
    container_name: httpd
    hostname: httpd
    networks:
      - mz8-network-1
    volumes:
      - apache2:/usr/local/apache2
    ports:
      - '8082:8082'
      - '8083:8083'
      - '8084:8084'


#################
#### VOLUMES ####
#################

volumes:
  jiradata:
    external: false
  confluencedatavar:
    external: false
  confluencedataopt:
    external: false
  owncloud:
    external: false

  postgresql-jira:
    external: false
  postgresql-confluence:
    external: false

#  mysqldata-jira:
#    external: false
#  mysql-confluence:
#    external: false
  mysqldata-oc:
    external: false

  apache2:
    external: false


##################
#### NETWORKS ####
##################

networks:
  mz8-network-1:
    driver: bridge
